modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT License"

[[mods]]
modId = "thornite_expansion"
displayName = "Thornite Expansion"
description = "Discover Thornite, a unique magical resource with nature's healing powers! Craft awesome tools and armor that fix themselves when you're hanging out near grass and flowers. Thanks, Mother Nature!"
version = "1.21.1-neo"
authors = "Euro307"
logoFile = "mod_banner.png"
logoBlur = false
displayURL = "https://github.com/euro308/ThorniteExpansion"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.thornite_expansion]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.92,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thornite_expansion]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "AFTER"
side = "BOTH"

[modproperties.thornite_expansion]
catalogueImageIcon = "mod_logo.png"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration